### ISSUE TITLE
Could the repo support private model?

### ISSUE THREAD

**Issue by Leixwx** [wuji3/visiondk#1]
thanks for your time, I know the repo supports some models in torchvision style, but I want to use my own model, what shall I do?

**Comment by wuji3** [comment]
The repo has not yet implemented the registration function of the custom model. If you want to use your own model, you need to implement it yourself, and write the function interface in utils/general.py, specifically in the [func]create_model method of [class]SmartModel
The function of custom models will be launched in the future，please stay tuned.
